export const nameCards: { [key: number]: {nome: string; categoria: string} } = {
    1: { nome: 'Fortune Rabbit', categoria: 'PG' },
    2: { nome: 'Fortune Tiger', categoria: 'PG' },
    3: { nome: 'Fortune Ox', categoria: 'PG' },
    4: { nome: 'Fortune Mouse', categoria: 'PG' },
    5: { nome: 'Fortune Dragon', categoria: 'PG' },
    6: { nome: 'Ganesha Gold', categoria: 'PG' },
    7: { nome: 'Wild Ape', categoria: 'PG' },
    8: { nome: 'Dragon Tiger Luck', categoria: 'PG' },
    9: { nome: 'Dragon Hatch', categoria: 'PG' },
    10: { nome: 'Bikini Paradise', categoria: 'PG' },
    11: { nome: 'Songkran Splash', categoria: 'PG' },
    12: { nome: 'Cash Mani', categoria: 'PG' },
    13: { nome: 'Jungle Delight', categoria: 'PG' },
    14: { nome: 'Muay Thai Champion', categoria: 'PG' },
    15: { nome: 'Wild Bandito', categoria: 'PG' },
    16: { nome: 'Super Market Spree', categoria: 'PG' },
    17: { nome: 'Ganesha Fortune', categoria: 'PG' },
    18: { nome: 'Piggy Gold', categoria: 'PG' },
    19: { nome: 'Circus Delight', categoria: 'PG' },
    20: { nome: 'Captains Bounty', categoria: 'PG' },
    21: { nome: 'Phoenix Rises', categoria: 'PG' },
    22: { nome: 'Midas Fortune', categoria: 'PG' },
    23: { nome: `Genie's 3 Wishes`, categoria: 'PG' },
    24: { nome: 'Hawaiian Tiki', categoria: 'PG' },
    25: { nome: 'Buffalo Win', categoria: 'PG' },
    26: { nome: 'Alchemy Gold', categoria: 'PG' },
    27: { nome: 'Tree Of Fortune', categoria: 'PG' },
    28: { nome: 'Diner Delights', categoria: 'PG' },
    29: { nome: 'Win Win WON', categoria: 'PG' },
    30: { nome: 'Totem Wonders', categoria: 'PG' },
    31: { nome: 'Mermaid Riches', categoria: 'PG' },
    32: { nome: 'Wild Bounty Showdown', categoria: 'PG' },
    33: { nome: 'Lucy Piggy', categoria: 'PG' },
    34: { nome: 'Mahjong Ways 2', categoria: 'PG' },
    35: { nome: 'Mahjong Ways', categoria: 'PG' },
    36: { nome: 'Ways Of The Qilin', categoria: 'PG' },
    37: { nome: 'Lucky Neko', categoria: 'PG' },
    38: { nome: 'Rise Of Apollo', categoria: 'PG' },
    39: { nome: 'Queen Of Bounty', categoria: 'PG' },
    40: { nome: 'Cocktail Nights', categoria: 'PG' },
    41: { nome: 'Leprechaun Riches', categoria: 'PG' },
    42: { nome: 'Prosperity Fortune Tree', categoria: 'PG' },
    43: { nome: 'Destiny Of Suns Moon', categoria: 'PG' },
    44: { nome: 'Candy Bonanza', categoria: 'PG' },
    45: { nome: 'Heist Stakes', categoria: 'PG' },
    46: { nome: `Emperor's Favour`, categoria: 'PG' },
    47: { nome: 'Butterfly Blossom', categoria: 'PG' },
    48: { nome: 'Prosperity Lion', categoria: 'PG' },
    49: { nome: 'Rooster Rumble', categoria: 'PG' },
    50: { nome: 'Dreams of Macau', categoria: 'PG' },
    51: { nome: 'Caishen Wins', categoria: 'PG' },
    52: { nome: 'Secrets Cleopatra', categoria: 'PG' },
    53: { nome: 'Medusa 1', categoria: 'PG' },
    54: { nome: 'Medusa 2', categoria: 'PG' },
    55: { nome: `Santa's Gift Rush`, categoria: 'PG' },
    56: { nome: 'Candy Burst', categoria: 'PG' },
    57: { nome: 'Guardians Of Ice & Fire', categoria: 'PG' },
    58: { nome: 'Fortune Gods', categoria: 'PG' },
    59: { nome: 'Legend Of Perseus', categoria: 'PG' },
    60: { nome: 'Speed Winner', categoria: 'PG' },
    61: { nome: 'Treasures Of Aztec', categoria: 'PG' },
    62: { nome: 'Jewels Of Prosperity', categoria: 'PG' },
    63: { nome: 'Crypto Gold', categoria: 'PG' },
    64: { nome: 'Dragon Legend', categoria: 'PG' },
    65: { nome: 'Journey To The Wealth', categoria: 'PG' },
    66: { nome: `Egypt's Book Mystery`, categoria: 'PG' },
    67: { nome: `Raider Jane's Crypt Of Fortune`, categoria: 'PG' },
    68: { nome: 'Legend Of Houyi', categoria: 'PG' },
    69: { nome: `The Queen's Banquet`, categoria: 'PG' },
    70: { nome: 'Mr Hallow-win', categoria: 'PG' },
    71: { nome: 'HipHop Panda', categoria: 'PG' },
    72: { nome: 'Garuda Gems', categoria: 'PG' },
    73: { nome: 'Pluship Frenzy', categoria: 'PG' },
    74: { nome: 'Wild Fireworks', categoria: 'PG' },
    75: { nome: '3 Monkeys', categoria: 'PG' },
    76: { nome: 'Monkey King', categoria: 'PG' },
    77: { nome: `Vampire's Charm`, categoria: 'PG' },
    78: { nome: 'Flirting Scholar', categoria: 'PG' },
    79: { nome: 'Groundhog Harvest', categoria: 'PG' },
    80: { nome: 'Emoji Riches', categoria: 'PG' },
    81: { nome: 'Farm Invaders', categoria: 'PG' },
    82: { nome: 'Mask Carnival', categoria: 'PG' },
    83: { nome: 'Shaolin Soccer', categoria: 'PG' },
    84: { nome: 'Wild Coaster', categoria: 'PG' },
    85: { nome: 'Thai Rivers Wonders', categoria: 'PG' },
    86: { nome: 'Battleground Royale', categoria: 'PG' },
    87: { nome: 'Galatic Gems', categoria: 'PG' },
    88: { nome: 'Hot Pot', categoria: 'PG' },
    89: { nome: 'Majestic Treasures', categoria: 'PG' },
    90: { nome: 'Opera Dynasty', categoria: 'PG' },
    91: { nome: 'Spirited Wonders', categoria: 'PG' },
    92: { nome: 'Nija Vs Samuray', categoria: 'PG' },
    93: { nome: 'Win Win Fish Prawh Crab', categoria: 'PG' },
    94: { nome: 'Reel Love', categoria: 'PG' },
    95: { nome: 'Sushi Oishi', categoria: 'PG' },
    96: { nome: 'Bali Vacation', categoria: 'PG' },
    97: { nome: 'Oriental Prosperity', categoria: 'PG' },
    98: { nome: 'Gem Saviour Sword', categoria: 'PG' },
    99: { nome: 'Wizdom Wonders', categoria: 'PG' },
    100: { nome: 'Gem Saviour Conquest', categoria: 'PG' },
    101: { nome: 'Symbolz Of Egypt', categoria: 'PG' },
    102: { nome: 'Honey Trap Of Diao Chan', categoria: 'PG' },
    103: { nome: `Jack Frost's Winter`, categoria: 'PG' },
    104: { nome: 'Hoods vs Wolf', categoria: 'PG' },
    105: { nome: 'Gem Saviour', categoria: 'PG' },
    106: { nome: 'Rave Party', categoria: 'PG' },
    107: { nome: 'Double Fortune', categoria: 'PG' },
    108: { nome: 'The Great Ice Scape', categoria: 'PG' },
    // JOGOS PP
    109: { nome: 'Fortune Of Giza', categoria: 'PP' },
    110: { nome: 'Cleocatra', categoria: 'PP' },
    111: { nome: 'Egyptian Fortunes', categoria: 'PP' },
    112: { nome: 'Gates of Olympus', categoria: 'PP' },
    113: { nome: 'Rise of Giza PowerNudge', categoria: 'PP' },
    114: { nome: 'Eye of Cleopatra', categoria: 'PP' },
    115: { nome: 'Gold Party', categoria: 'PP' },
    116: { nome: 'Spirit of Adventure', categoria: 'PP' },
    117: { nome: 'Christmas Big Bass Bonanza', categoria: 'PP' },
    118: { nome: 'Cash Bonanza', categoria: 'PP' },
    119: { nome: 'Drill That Gold', categoria: 'PP' },
    120: { nome: 'Chicken Chase', categoria: 'PP' },
    121: { nome: 'Queenie', categoria: 'PP' },
    122: { nome: 'The Ultimate 5', categoria: 'PP' },
    123: { nome: 'Rock Vegas', categoria: 'PP' },
    124: { nome: 'Wild Depths', categoria: 'PP' },
    125: { nome: `Magician's Secrets`, categoria: 'PP' },
    126: { nome: 'Crystal Caverns Megaways', categoria: 'PP' },
    127: { nome: 'Smugglers Cove', categoria: 'PP' },
    128: { nome: 'Super X', categoria: 'PP' },
    129: { nome: 'Bounty Gold', categoria: 'PP' },
    130: { nome: 'Book Of Fallen', categoria: 'PP' },
    131: { nome: `Santa's Wonderland`, categoria: 'PP' },
    132: { nome: 'Big Juan', categoria: 'PP' },
    133: { nome: 'Star Pirates Code', categoria: 'PP' },
    134: { nome: 'Mystic Chief', categoria: 'PP' },
    135: { nome: 'Day Of Dead', categoria: 'PP' },
    136: { nome: 'Piggy Bank Bills', categoria: 'PP' },
    137: { nome: 'Treasure Wild', categoria: 'PP' },
    138: { nome: 'Starlight Princess', categoria: 'PP' },
};